const Router = require("express")
const router = new Router()
const userController = require("../Controllers/UserController")
const isAuth = require('../middleware/isAuth')
const bestPairsController = require("../Controllers/bestpairsController")

router.post("/login", userController.login)
router.post("/register", userController.registration)
router.delete("/admin/users/:id", userController.delete)
router.get("/admin/users/", userController.all)
router.get("/checkme", isAuth, userController.getme)
router.post("/subscription", isAuth, userController.subscription)
router.post("/request_wallet", userController.requestWallet)
router.get("/refs", isAuth, userController.getMyRefs)
router.get("/chat_settings", userController.getChatSettings)
router.get("/bestpairs", bestPairsController.getBestPairs)
router.get("/stat", isAuth, userController.stat)
router.get("/check_recovery", userController.checkRecovery)
router.post("/change_password", isAuth, userController.changePassword)
router.get("/myvisits", isAuth, userController.getMyVisits)
router.post("/forget", userController.forget)
module.exports = router